name: Deploy Sphinx Docs

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not 'main'

jobs:
  build_docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Ensure full history is fetched for Git actions

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Use your desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install sphinx sphinx_rtd_theme myst-parser nbsphinx

    - name: Build Sphinx documentation
      run: |
        sudo apt-get install pandoc
        cd docs
        ./sync_notebooks.sh
        ./autoapidoc.sh
        make html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build/html
        publish_branch: gh-pages
